[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "@interop-lib/=lib/interop-lib/src/"]
solc_version = "0.8.20"
optimize = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"
# liskSepolia = "${LISK_RPC}"
op_sepolia = "${OP_SEPOLIA}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# liskSepolia  = { key  = "${ETHERSAN_API_KEY}" }
op_sepolia = { key = "${OPSCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_KEY}" }
base = { key = "${BASESCAN_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
